# importing required library 

numpy for creating dummy dataset. 

sklearn library to perform train_test_split of the given dataset

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

# Dummy data using arange function

In [2]:
dataset = np.arange(10)

In [3]:
#train_test for the given dataset
X_train, X_test = train_test_split(dataset, test_size = 4)

Actual data

In [4]:
dataset

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Train data i.e. 60% data split for training and 40% for testing

In [5]:
X_train

array([1, 9, 2, 8, 3, 0])

In [6]:
X_test

array([5, 4, 6, 7])